### ISSUE TITLE
Add Autonav Challenge Trajectories and Trajectory Class

### ISSUE THREAD

**Issue by vatanaksoytezer** [sneakysnakesfrc/robot-2021#14]
- Create a trajectory class (like SneakyTrajectory from 2020 code).
- Find out optimum trajectories using FalconDashboard and cubic clamped method.
- For galactic search challenge find each possible trajectory (red only and blue only) and find another trajectory that passes from both red and blue together.
- Add trajectories and related auto commands (including intaking) to code base.

@OVEYMTarik57 @KahramanAkyuz you can share the workload and work together. Deadline is Saturday 13th 23:59.

Later on an issue about testing these in simulator will be assigned.

**Comment by tariqyilmaz** [comment]
@vatanaksoytezer I'm telling you to move on. Old trajectory deleted. After Add Encoder, Gyro etc., Add Drive PID and Code is Fixed.

**Comment by vatanaksoytezer** [comment]
Closed by #15
