### ISSUE TITLE
Shooter Joystick Functionality

### ISSUE THREAD

**Issue by vatanaksoytezer** [sneakysnakesfrc/robot-2021#5]
Shooter kodunun joystick fonksiyonlarının yazılması

**Comment by tariqyilmaz** [comment]
Intake ile shooter aynı branch içerisine yapıldı. Robotconteiner a eklendi. ToggleIntake ile intake i aç kapa yapıldı. ToggleCompressor ile robotun hava tankları dolması için gereken kod yazıldı. Extra düzeltme falan gerekirse haber verirsin abi.
Master a atıp pushluyorum.

**Comment by vatanaksoytezer** [comment]
Solved with #7

**Comment by vatanaksoytezer** [comment]
Solved by #9
